### ISSUE TITLE
Fails to compile in TrueOS

### ISSUE THREAD

**Issue by PeterSprague** [jceel/py-libzfs#18]
I'm getting the same error building as Issue #16 on latest TrueOS on generic amd64 workstation. Everything has been updated today including sources git pull.

py3-libzfs port also fails with same error.

Mentioned "hack" does not work for me.

S uname -a
FreeBSD xxxxxxxxxxx 12.0-CURRENT FreeBSD 12.0-CURRENT #1 96a971c9a(drm-next): Mon Apr 17 18:50:02 UTC 2017 root@devastator:/usr/obj/usr/src/sys/GENERIC amd64
$ uname -K
1200027

$ bash
$ export UNAME_K=1200027
$ python3.6 setup.py build
running build
running build_py
creating build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying converter.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying nvpair.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.html -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
copying libzfs.c -> build/lib.freebsd-12.0-CURRENT-amd64-3.6
running build_ext
skipping 'libzfs.c' Cython extension (up-to-date)
building 'libzfs' extension
cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC -I/usr/src/cddl/lib/libumem -I/usr/src/sys/cddl/compat/opensolaris/ -I/usr/src/sys/cddl/compat/opensolaris -I/usr/src/cddl/compat/opensolaris/include -I/usr/src/cddl/compat/opensolaris/lib/libumem -I/usr/src/cddl/contrib/opensolaris/lib/libzpool/common -I/usr/src/sys/cddl/contrib/opensolaris/common/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/fs/zfs -I/usr/src/sys/cddl/contrib/opensolaris/uts/common/sys -I/usr/src/cddl/contrib/opensolaris/head -I/usr/src/sys/cddl/contrib/opensolaris/uts/common -I/usr/src/cddl/contrib/opensolaris/lib/libnvpair -I/usr/src/cddl/contrib/opensolaris/lib/libuutil/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs/common -I/usr/src/cddl/contrib/opensolaris/lib/libzfs_core/common -I/usr/local/include/python3.6m -c libzfs.c -o build/temp.freebsd-12.0-CURRENT-amd64-3.6/libzfs.o -DNEED_SOLARIS_BOOLEAN -D_XPG6 -g -O0
libzfs.c:705:42: error: use of undeclared identifier 'ZFS_MAX_DATASET_NAME_LEN'
__pyx_e_6libzfs_MAX_DATASET_NAME_LEN = ZFS_MAX_DATASET_NAME_LEN
^
libzfs.c:19646:73: warning: incompatible pointer to integer conversion passing 'PyObject *' (aka 'struct _object *') to parameter of type 'zfs_type_t'
[-Wint-conversion]
__pyx_v_handle = zfs_path_to_zhandle(__pyx_v_self->handle, __pyx_t_1, __pyx_t_3);
^~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:700:79: note: passing argument to parameter here
extern zfs_handle_t *zfs_path_to_zhandle(libzfs_handle_t *, char *, zfs_type_t);
^
libzfs.c:50733:74: warning: passing 'const char *' to parameter of type 'char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
__pyx_v_ret = zfs_destroy_snaps(__pyx_v_self->__pyx_base.handle, __pyx_v_c_name, 1);
^~~~~~~~~~~~~~
/usr/src/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h:563:52: note: passing argument to parameter here
extern int zfs_destroy_snaps(zfs_handle_t *, char *, boolean_t);
^
2 warnings and 1 error generated.
error: command 'cc' failed with exit status 1

Solution?

**Comment by mexicarne** [comment]
The same here with FreeBSD port on 12.0-CURRENT r318249 with python 2.7
